# Generated by Django 5.1 on 2024-09-03 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='artist/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'svg', 'webp'])])),
                ('bio', models.TextField(validators=[django.core.validators.MaxLengthValidator(2500)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'svg', 'webp'])])),
                ('audio_file', models.FileField(upload_to='music', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'ogg', 'wav', 'aac', 'mp4'])])),
                ('audio_link', models.CharField(blank=True, max_length=255, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
